<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalParquetProject)' == 'true' and '$(TargetFramework)' != 'net48'">
    <ProjectReference Include="$(ParquetProjectPath)" />
  </ItemGroup>

  <ItemGroup Condition="'$(UseLocalParquetProject)' != 'true'">
    <PackageReference Include="kiloOhm.Parquet.Net" Version="$(ParquetNetVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Parquet.Query\Parquet.Query.csproj" />
  </ItemGroup>

</Project>
